[package]
name = "polars_deltalake"
version = "0.3.0"
edition = "2021"

[lib]
name = "polars_deltalake"
crate-type = ["cdylib"]

[dependencies]
polars = { version = "0.41.3", features = ["parquet", "cloud", "azure", "aws", "gcp", "async", "dtype-struct", "dtype-decimal"]}
polars-lazy ={ version = "0.41.3",  features = ["parquet","cloud", "async", "diagonal_concat"]}
polars-plan = {version = "0.41.3", features = ["parquet","cloud", "async"]}
polars-arrow = {version = "0.41.3"}
pyo3 = { version = "0.21", features = ["extension-module", "abi3", "abi3-py38"] }
pyo3-polars = { version = "0.15.0", features = ["derive", "lazy"] }
serde = { version = "*", features = ["derive"] }
delta_kernel = {version = "0.3",  default-features = false}
tokio = { version = "*", features = ["rt-multi-thread"] }
thiserror = { version = "1" }
itertools = {version = "*"}
serde_json = "1"
tracing = { version = "*"}

[target.'cfg(target_os = "linux")'.dependencies]
jemallocator = { version = "0.5", features = ["disable_initial_exec_tls"] }

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"
